---
- name: install kafka
  hosts: kafkaserver1
  become: yes
  become_user: dojokafka
  tasks:
    # - name: copy of kafka binaries
    #   copy:
    #     src: /Users/jagyasenidas/Documents/DOJO/Day2/Mini-kafka/Dojo-Mini-Kafka/files/kafka_2.13-3.2.0.tar
    #     dest: /home/dojokafka/
    #     owner: dojokafka
    #     group: dojo
    #     mode: 0644

    # - name: Extract the tar files
    #   unarchive:
    #     src: /home/dojokafka/kafka_2.13-3.2.0.tgz
    #     dest: /home/dojokafka/
    #     owner: dojokafka
    #     group: dojo
    #     mode: 0755
    #     remote_src: yes