---
- name: install kafka
  hosts: kafkaserver1
  become: yes
  become_user: dojokafka
  tasks:
    # - name: copy of kafka binaries
    #   copy:
    #     src: /Users/jagyasenidas/Documents/DOJO/Day2/Mini-kafka/Dojo-Mini-Kafka/files/kafka_2.13-3.2.0.tar
    #     dest: /home/dojokafka/
    #     owner: dojokafka
    #     group: dojo
    #     mode: 0644

    # - name: Extract the tar files
    #   unarchive:
    #     src: /home/dojokafka/kafka_2.13-3.2.0.tgz
    #     dest: /home/dojokafka/
    #     owner: dojokafka
    #     group: dojo
    #     mode: 0755
    #     remote_src: yes

    # - name: copy the java
    #   copy:
    #     src: /Users/jagyasenidas/Documents/JAVA/jdk-17_macos-aarch64_bin.tar
    #     dest: /home/dojokafka/
    #     owner: dojokafka
    #     group: dojo
    #     mode: 0644

    # - name: Extract the tar files
    #   unarchive:
    #     src: /home/dojokafka/jdk-17_macos-aarch64_bin.tar
    #     dest: /home/dojokafka/
    #     owner: dojokafka
    #     group: dojo
    #     mode: 0755
    #     remote_src: yes
    - name: Creating symbolic link
      become: yes
      become_user: dojokafka
      file: 
        src: kafka_2.13-3.2.0
        dest: '{{ base }}'
        owner: dojokafka
        group: dojo
        state: link

    # - name: Create link
    #   become: yes
    #   become_user: dojokafka
    #   shell: ln -s kafka_2.13-3.2.0 kafka
    #   warn: false
    #   args:
    #     chdir: /home/dojokafka
    #     warn: true

    - name: Start Kafka
      shell: bin/zookeeper-server-start.sh config/zookeeper.properties >/home/dojokafka/kafka-start.log
      args: 
        chdir: /home/dojokafka/kafka
        warn: false

    - name: Copy service files
      become: yes
      copy:
        src:  '{{ item }}'
        dest: /etc/systemd/system
        owner: root
        group: root
        force: no
      with_items:
        - zookeeper.service
        - kafka.service
      
    - name: Configure kafka connect
      become: yes
      become_user: dojokafka
      lineinfile:
        path: "{{ base }}/config/connect-standalone.properties"
        regexp: '^plugin.path'
        line: "plugin.path={{ base }}/libs/connect-file-3.2.0.jar"

    - name: Creating test file
      become: yes
      become_user: dojokafka
      copy:
        dest: "{{ base }}/test.txt"
        content: |
          testing 1
          testing 2
    - name: Updating test file sink path
      become: yes
      become_user: dojokafka
      lineinfile:
        path: "{{ base }}/config/connect-file-sink.properties"
        regexp: '^file=test.sink.txt'
        line: "file={{ base }}/test.sink.txt"